# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build book

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install jupyter-book
    - name: Build book
      run: jb build .
    - name: Commit the book
      uses: s0/git-publish-subdir-action@v2.4.0
      env:
        REPO: self
        BRANCH: generated
        FOLDER: _build
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
